version: '3.7'

services:

  wikimed-backend:
    image: emrecalik/wikimed-server:0.0.1-SNAPSHOT
    restart: always
    networks:
      - wikimed-network
    ports:
      - 8080:8080
    mem_limit: 700M
    depends_on:
      - wikimed-mysql

  wikimed-mysql:
    image: emrecalik/wikimed-db:0.0.1-SNAPSHOT
    networks:
      - wikimed-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=emre1905
      - MYSQL_DATABASE=wikimed_db
    volumes:
      - vikimed-volume:/var/lib/mysql
    mem_limit: 700M

networks:
  wikimed-network:

volumes:
  wikimed-volume: