version: '3.7'

services:

  wikimed-backend:
    image: emrecalik/wikimed-server
    restart: always
    networks:
      - wikimed-network
    ports:
      - 8080:8080
    depends_on:
      - wikimed-mysql

  wikimed-mysql:
    image: emrecalik/wikimed-db
    networks:
      - wikimed-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=emre1905
      - MYSQL_DATABASE=wikimed_db

networks:
  wikimed-network: