version: '3'

services:

  wikimed-backend:
    image: emrecalik/swe-573
    restart: always
    networks:
      - wikimed-network
    ports:
      - 8080:8080
    depends_on:
      - course-registration-mysql

  wikimed-mysql:
    image: mysql:8
    networks:
      - course-registration-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=emre1905
      - MYSQL_DATABASE=registrationdb

networks:
  wikimed-network: